# Spark DataFrame Basic Operations

In [2]:
from pyspark.sql import SparkSession

In [3]:
spark = SparkSession.builder.appName('oops').getOrCreate()

In [5]:
df = spark.read.csv('appl_stock.csv', inferSchema = True, header = True)

In [6]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [7]:
df.show()

+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|               Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04 00:00:00|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05 00:00:00|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06 00:00:00|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07 00:00:00|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08 00:00:00|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11 00:00:00|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12 00:00:00|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13 00:00:00|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14 00:00:00|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15 00:00:00|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19 00:00:00|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20 00:00:00|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21 00:00:00|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22 00:00:00|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25 00:00:00|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26 00:00:00|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27 00:00:00|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28 00:00:00|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29 00:00:00|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01 00:00:00|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [11]:
df.filter("Close < 200").select(["Open", "Close"]).show()

+------------------+------------------+
|              Open|             Close|
+------------------+------------------+
|206.78000600000001|            197.75|
|        204.930004|        199.289995|
|        201.079996|        192.060003|
|192.36999699999998|        194.729998|
|        195.909998|        195.859997|
|        195.169994|        199.229994|
|        196.730003|        192.050003|
|192.63000300000002|        195.460001|
|        195.690006|194.11999699999998|
|        196.419996|196.19000400000002|
|        195.889997|195.12000700000002|
|        194.880001|        198.669994|
|        199.999998|        197.059998|
|         92.699997|         93.699997|
|         94.730003|             94.25|
|         94.129997|         93.860001|
|         94.040001|         92.290001|
|         92.199997|         91.279999|
|         91.510002|         92.199997|
|         92.309998| 92.08000200000001|
+------------------+------------------+
only showing top 20 rows

In [13]:
df.filter(df['Close'] < 200).select(["Open", "Close"]).show()

+------------------+------------------+
|              Open|             Close|
+------------------+------------------+
|206.78000600000001|            197.75|
|        204.930004|        199.289995|
|        201.079996|        192.060003|
|192.36999699999998|        194.729998|
|        195.909998|        195.859997|
|        195.169994|        199.229994|
|        196.730003|        192.050003|
|192.63000300000002|        195.460001|
|        195.690006|194.11999699999998|
|        196.419996|196.19000400000002|
|        195.889997|195.12000700000002|
|        194.880001|        198.669994|
|        199.999998|        197.059998|
|         92.699997|         93.699997|
|         94.730003|             94.25|
|         94.129997|         93.860001|
|         94.040001|         92.290001|
|         92.199997|         91.279999|
|         91.510002|         92.199997|
|         92.309998| 92.08000200000001|
+------------------+------------------+
only showing top 20 rows

In [15]:
df.filter( (df['Open'] > 100) & (df['Close'] < 100) ).show()

+-------------------+------------------+----------+-----------------+---------+---------+-----------------+
|               Date|              Open|      High|              Low|    Close|   Volume|        Adj Close|
+-------------------+------------------+----------+-----------------+---------+---------+-----------------+
|2014-09-03 00:00:00|        103.099998|103.199997|98.58000200000001|98.940002|125421000|94.34521099999999|
|2014-09-25 00:00:00|        100.510002|100.709999|        97.720001|97.870003|100092000|93.32490200000001|
|2014-10-01 00:00:00|        100.589996|100.690002|        98.699997|    99.18| 51491300|        94.574063|
|2014-10-13 00:00:00|101.33000200000001|101.779999|        99.809998|99.809998| 53583400|        95.174803|
|2014-10-14 00:00:00|        100.389999|100.519997|            98.57|    98.75| 63688600|94.16403199999999|
|2016-01-12 00:00:00|        100.550003|100.690002|        98.839996|99.959999| 49154200|        97.362258|
|2016-01-13 00:00:00|            100.32|101.190002|        97.300003|97.389999| 62439600|        94.859047|
|2016-01-25 00:00:00|        101.519997|101.529999|        99.209999|99.440002| 51794500|        96.855775|
+-------------------+------------------+----------+-----------------+---------+---------+-----------------+

In [16]:
df.filter(df['Open'] > 100).filter(df['Close'] < 100).show()

+-------------------+------------------+----------+-----------------+---------+---------+-----------------+
|               Date|              Open|      High|              Low|    Close|   Volume|        Adj Close|
+-------------------+------------------+----------+-----------------+---------+---------+-----------------+
|2014-09-03 00:00:00|        103.099998|103.199997|98.58000200000001|98.940002|125421000|94.34521099999999|
|2014-09-25 00:00:00|        100.510002|100.709999|        97.720001|97.870003|100092000|93.32490200000001|
|2014-10-01 00:00:00|        100.589996|100.690002|        98.699997|    99.18| 51491300|        94.574063|
|2014-10-13 00:00:00|101.33000200000001|101.779999|        99.809998|99.809998| 53583400|        95.174803|
|2014-10-14 00:00:00|        100.389999|100.519997|            98.57|    98.75| 63688600|94.16403199999999|
|2016-01-12 00:00:00|        100.550003|100.690002|        98.839996|99.959999| 49154200|        97.362258|
|2016-01-13 00:00:00|            100.32|101.190002|        97.300003|97.389999| 62439600|        94.859047|
|2016-01-25 00:00:00|        101.519997|101.529999|        99.209999|99.440002| 51794500|        96.855775|
+-------------------+------------------+----------+-----------------+---------+---------+-----------------+

In [17]:
df.filter(df['Low'] == 197.16).select("Date").show()

+-------------------+
|               Date|
+-------------------+
|2010-01-22 00:00:00|
+-------------------+

In [21]:
result = df.filter(df['Low'] == 197.16).collect()

In [23]:
result

[Row(Date=datetime.datetime(2010, 1, 22, 0, 0), Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)]

In [24]:
result[0]

Row(Date=datetime.datetime(2010, 1, 22, 0, 0), Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)

In [25]:
row = result[0]

In [28]:
dic = row.asDict()

In [30]:
dic

{'Date': datetime.datetime(2010, 1, 22, 0, 0),
 'Open': 206.78000600000001,
 'High': 207.499996,
 'Low': 197.16,
 'Close': 197.75,
 'Volume': 220441900,
 'Adj Close': 25.620401}

In [31]:
dic["Volume"]

220441900